name: mautic
recipe: lamp
config:
  webroot: .
  php: "7.2"
  database: mysql:5.7
  xdebug: true

services:
  appserver:
    build:
      - "cd /app && composer install"
    overrides:
      environment:
        PHP_IDE_CONFIG: "serverName=mautic.lndo.site"

tooling:
  php:
    service: appserver
  segment-update:
    service: appserver
    cmd: php /app/app/console mautic:segments:update
  campaigns-update:
    service: appserver
    cmd: php /app/app/console mautic:campaigns:update
  campaigns-trigger:
    service: appserver
    cmd: php /app/app/console mautic:campaigns:trigger
  hubspot-push:
    service: appserver
    cmd: php /app/app/console mautic:integration:pushleadactivity --integration=Hubspot
  hubspot-fetch:
    service: appserver
    cmd: php /app/app/console mautic:integration:fetchleads --integration=Hubspot
  phpunit:
    service: appserver
    cmd: /app/bin/phpunit
  test:
    service: appserver
    description: Run Tests Locally
    cmd:
      - appserver: composer test

