name: mautic
recipe: lamp
config:
  webroot: .
  php: "7.2"
  database: mysql:5.7

services:
  appserver:
    build:
      - "cd /app && composer install"

tooling:
  phpunit:
    service: appserver
    cmd: /app/bin/phpunit
  test:
    service: appserver
    description: Run Tests Locally
    cmd:
      - appserver: composer test
